/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-5c83056b54cc41be84c554fb6404c7fd
Title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/earth.gltf')
  const { actions } = useAnimations(animations, group)
  
  return (
    <group ref={group} {...props} dispose={null} position={[2.5,2,3]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
          <group name="EarthFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Earth" rotation={[-1.833, 0, 0]}>
                  <mesh name="Earth_01_-_Default_0" geometry={nodes['Earth_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                </group>
                <group name="Moon" rotation={[-1.617, -.258, 1.39]} scale={0.27}>
                  <mesh name="Moon_02_-_Default_0" geometry={nodes['Moon_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                </group>
                <group name="Clouds" rotation={[-1.833, 0, 0]} scale={[1.01, 1.029, 1.029]}>
                  <mesh name="Clouds_03_-_Default_0" geometry={nodes['Clouds_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth.gltf')
