/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ufo.gltf 
Author: sebslom (https://sketchfab.com/sebslom)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-75655f43c4fc4c56ab60746caf7119fe
Title: UFO
*/

import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
export default function Model(props) {
  const { nodes, materials } = useGLTF('/ufo.gltf');
  const groupRef = useRef();
  const [direction, setDirection] = useState(1);
  const speed = 0.02;
  const maxPosition = 10;
  const handleClick = () => {
    window.open('https://buy.stripe.com/test_4gwfZqdPzdbscFOdQQ', '_blank');
  };
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.position.x += direction * speed;
      if (groupRef.current.position.x > maxPosition || groupRef.current.position.x < -maxPosition) {
        setDirection(-direction); 
      }
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} position={[0, 5, -5]} onClick={handleClick}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.DefaultMaterial}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={.5}
          />
        </group>
      </group>
    </group>
  );
}
useGLTF.preload('/ufo.gltf');
