/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 uranus.gltf 
Author: uperesito (https://sketchfab.com/uperesito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/urano-b89a7d4c0f5147129b7fbac98ce70888
Title: Urano
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/uranus.gltf')
  return (
    <group {...props} dispose={null} position={[8.5,2,3]}>
      <group rotation={[-1.703, 0, 0]} scale={.0009}>
        <mesh geometry={nodes.Esfera_Mat1_0.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Esfera_Mat1_0_1.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Esfera_Mat1_0_2.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Esfera_Mat1_0_3.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Esfera_Mat1_0_4.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Esfera_Mat1_0_5.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Esfera_Mat1_0_6.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Esfera_Mat1_0_7.geometry} material={materials['Mat.1']} />
      </group>
      <group rotation={[0.135, 0, 0]} scale={.0008}>
        <mesh geometry={nodes.Plano_Mat_0.geometry} material={materials.material} position={[-450, 50, 0]} rotation={[-0.27, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/uranus.gltf')
